version: '3.8'

services:
  consultafacil_mysql:
    image: mysql:8.0
    container_name: consultafacil_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consultafacil_db
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: brunaczaramela/consulta-facil:1.2
    container_name: consultafacil_app
    restart: always
    depends_on:
      - consultafacil_mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://consultafacil_mysql:3306/consultafacil_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

volumes:
  mysql_data: